plugins:
  - jekyll-relative-links
#   - jekyll-feed
#   - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - PRIVACY_POLICY.md
  - README.md

theme: jekyll-theme-cayman

safe: true

# header_pages:
#   - README.md
#   - PRIVACY_POLICY.md

title: World Geography Title in _config.yml
description: January 2021
