plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - PRIVACY_POLICY.md

theme: jekyll-theme-cayman

safe: true

header_pages:
  - README.md
  - PRIVACY_POLICY.md
