title: World Geography
description: The best app in Google Play Store for World Geography quiz

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - privacy_policy.md
  - README.md
  - terms_of_service.md
  
theme: jekyll-theme-cayman

safe: true

# Disable "View on GitHub" button
github:
  is_project_page: false
